---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-files
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs
  resources:
    requests:
      storage: 5Gi # Don't matter, it's elastic
