apiVersion: v1
kind: Secret
metadata:
  name: rds-credentials
type: Opaque
data:
  DB_HOST: cHJvZC1yZHMtaWRlbnRpZmllci5jM2dlZzYyNmtuaTgudXMtd2VzdC0yLnJkcy5hbWF6b25hd3MuY29t
  DB_USERNAME: YWRtaW4=
  DB_PASSWORD: QmljcyQyMDI0
  DB_DATABASE: cHJvZHJkcw==
